/* All free solid fontawesome icons -> https://fontawesome.com/icons?d=gallery&s=solid&m=free */

import {
    faAngleDoubleLeft,
    faAngleDoubleRight,
    faAngleDown,
    faAngleRight,
    faArrowLeft,
    faBars,
    faBookOpen,
    faChartArea,
    faChartBar,
    faChartPie,
    faChevronDown,
    faChevronUp,
    faColumns,
    faDownload,
    faEye,
    faFile,
    faPrint,
    faSearch,
    faTable,
    faTachometerAlt,
    faTimes,
    faTrashAlt,
    faUser,
    faPlus
} from '@fortawesome/free-solid-svg-icons';

export const fontAwesomeSolidIcons = {
    faAngleDoubleLeft,
    faAngleDoubleRight,
    faAngleDown,
    faAngleRight,
    faArrowLeft,
    faBars,
    faBookOpen,
    faChartArea,
    faChartBar,
    faChartPie,
    faChevronDown,
    faChevronUp,
    faColumns,
    faSearch,
    faTable,
    faTachometerAlt,
    faUser,
    faTrashAlt,
    faTimes,
    faDownload,
    faEye,
    faPrint,
    faFile,
    faPlus
};
